name: Rust Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-tests:
    name: MintVM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # GitHub Actions supports rustup by default, so we can install the toolchain directly
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all
