name: Rust Clippy Check

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy-check:
    name: MintVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup component add clippy

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features
